#!/bin/bash

while read filepath
do
  if [[ "$filepath" == *maven-fragments/* ]]; then
     echo "$filepath" | /usr/lib/rpm/maven.req
  fi
  if [[ "$filepath" =~ .*/share/javadoc/.* ]]; then
     echo "$filepath" | /usr/lib/rpm/javadoc.req
  fi
done < "${1:-/proc/${$}/fd/0}"
